use assignment_3;
create table employee(emp_id int(10),f_name varchar(20),l_name varchar(10),job_type varchar(10),salary int(20),dept varchar(10),commision int(10),manager_id int(10));
alter table employee add (doj date);
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,doj) values(1,'Arun','Khan','Manager',90000,'Production','1998-01-04');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,doj) values(2,'Barun','Kumar','Manager',80000,'Marketing','1998-02-09');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(3,'Chitra','Kapoor','Engineer',60000,'Production',1,'1998-01-08');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(4,'Deeraj','Mishra','Manager',75000,'Sales',4,'2001-12-27');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(5,'Emma','Dutta','Engineer',55000,'Production',1,'2002-03-20');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,doj) values(6,'Chinaswami','Iyer','Accounts',70000,'Accounts','2001-07-16');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(7,'Deeraj','Kumar','Clerk',40000,'Accounts',6,'2016-12-16');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,doj) values(8,'Mr.','Paul','Engineer',60000,'R&D','2014-09-06');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(9,'Raj','Mishra','Clerk',30000,'Sales',4,'2018-03-27');
insert into employee(emp_id,f_name,l_name,job_type,salary,commision,dept,manager_id,doj) values(10,'Sunny','Deol','Salesman',20000,10000,'Marketing',2,'2003-03-31');
insert into employee(emp_id,f_name,l_name,job_type,salary,dept,manager_id,doj) values(11,'Bobby','Deol','Engineer',35000,'R&D',8,'2017-10-07');
insert into employee(emp_id,f_name,l_name,job_type,salary,commision,dept,manager_id,doj) values(10,'Choton','Khan','Salesman',15000,5000,'Marketing',2,'2013-05-11');
select * from employee;
select f_name,l_name,job_type from employee;
create table department (d_name varchar(10) primary key,d_loc varchar(10),HOD_id int(10));
insert into department (d_name,d_loc,HOD_id) values('Sales','Kol',4);
insert into department (d_name,d_loc,HOD_id) values('Accounts','Delhi',6);
insert into department (d_name,d_loc,HOD_id) values('Production','Kol',1);
insert into department (d_name,d_loc,HOD_id) values('Marketing','Kol',2);
insert into department (d_name,d_loc,HOD_id) values('R&D','Marketing',8);
select * from department;
select d_name from department;
select f_name,l_name from employee where dept='sales';
select f_name,l_name from employee where salary>50000;
select emp_id,f_name,l_name,salary,dept,job_type from employee where manager_id!=1;
select emp_id,f_name,l_name,dept,job_type from employee where salary>40000 and salary<70000;
select emp_id,f_name,l_name,salary,dept,job_type from employee where manager_id>0 and manager_id<9;
select f_name,salary from employee where l_name like 'k%';
select f_name,salary from employee where l_name like 'k%' and l_name like '%r';
select emp_id,f_name,l_name,dept,job_type from employee where l_name like '__o%';
select emp_id,f_name,l_name,dept,job_type from employee where job_type='engineer' and salary>50000;
select emp_id,f_name,l_name,dept,job_type from employee where dept='production' and salary>60000;
select min(salary),max(salary),avg(salary),sum(salary) from employee where dept='sales';
select f_name,l_name from employee order by f_name,l_name ASC;
select dept,count(dept) from employee group by dept;
select count(dept) from employee;
select avg(commision) from employee; 
select avg(salary),dept from employee group by dept;
select job_type,sum(salary),dept from employee group by dept;
select dept,avg(salary) from employee where salary>40000 group by dept;
select dept,max(salary) from employee where salary>50000 group by dept;
select job_type,sum(salary) from employee where salary<100000 group by job_type;
select dept,avg(salary) from employee group by dept having avg(salary)=(select max(avg(salary)) from employee group by dept);