use assignment_3;
select upper('joy mohunbagan'), lower('JOY MOHUNBAGAN');
create table student(f_name varchar(20),l_name varchar(10));
insert into student(f_name,l_name) values('Chinnaswami','Iyer');
insert into student(f_name,l_name) values('Sribasana','Iyer');
select concat(f_name,l_name) from student;
select instr("sch","3") as matchposition;
select length('joymohunbagan');
select sqrt(amount) from table_name;
select power(4,2);
select ceil(25.75);
select substr("Joy Mohunbagan",5,3) as extractstring;
create table price(id int(10),price int(10));
insert into price(id,price) values(1,50);
insert into price(id,price) values(2,100);
insert into price(id,price) values(3,150);
select * from price;
select max(price) as largestprice from price;
select min(price) as smallestprice from price;
select round(25.51) as roundvalue;
select avg(price) from price;
select count(id) from price;
select exp(1);
select mod(18,4);
select ceiling(14.887) as ceilvalue, floor(14.887) as floorvalue;
select round(11.11111111) as roundvalue;
select power(8,7);
select getdate();
select * from employee where extract (year from age(current_date,hire-date)>1);
select months_between (to_date('02-02-2015','MM-DD-YYYY'), to_date('12-01-2014','MM-DD-YYYY'))"Months" from dual;
select to_char(add_months(hire_date,1),'DD-MM-YYYY')"next months" from dual;
select next_day('12-MAR-2015','MONDAY')"Next Day" from dual;
select last_day("2022-09-09");
select round(1.1,2); 
select turncate(135.375,2);
select to_char(add_months(hire_date,1),'DD-MM-YYYY')"Next Month" from dual;
update employee set salary=salary+(salary*10/100);
update employee set marketing=marketing+(marketing*20/100);